name: 'joinr_data_model'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'joinr_dbt_dev'

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  facebook_ads_database: fivetran_test
  facebook_ads_schema: joinr_mvp_facebook_1
  google_ads_database: fivetran_test
  google_ads_schema: joinr_mvp_google_1
  target_database: dbt_test
  target_schema: lumenad

models:
  joinr_data_model:
    +schema: # leave blank for just the target_schema
    +materialized: table
    tmp:
      +materialized: view
